name: CI

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev pkg-config

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test

    # do not want to treat warning as errors rn, still here for reference
    - name: Run clippy
      run: cargo clippy
    
    - name: Generate Docs and Save
      run: |
      ./generate_docs.sh  # Adjust the path if necessary
      git add docs
      git config --local user.email "action@github.com"
      git config --local user.name "GitHub Action"
      git commit -m "Add generated docs" --no-verify
      git push

